apiVersion: v1
kind: PersistentVolume
metadata:
  name: sre-postgres-pv
  labels:
    app: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
